### ISSUE TITLE
globulin & carbohydrate

### ISSUE THREAD

**Issue by sadikkuzu** [altuga/coreeffectivejava#1]
Merhaba,
`globulin` ve `carbohydrate` değer takası olmuş:

https://github.com/altuga/effectivejava_hoca/blob/042fb07dd489f901f9646d5a0a4b713e81e236de/src/main/java/org/effectivejava/examples/chapter02/item02/kodcu/builder/Serum.java#L59-L60

**Comment by altuga** [comment]
Düzeltildi. Geri bildirim için teşekkürler.
